services:
  db:
    image: postgres:16
    container_name: dresscode-db
    environment:
      POSTGRES_USER: dresscode
      POSTGRES_PASSWORD: dresscode
      POSTGRES_DB: dresscode
    ports:
      - "5432:5432"
    volumes:
      - dresscode_db:/var/lib/postgresql/data

volumes:
  dresscode_db: